//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem.App.ReportService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReportService.ReportSoapServiceSoap")]
    public interface ReportSoapServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMostBorrowedBooks", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LibrarySystem.App.ReportService.ResponseOfDataTable GetMostBorrowedBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMostBorrowedBooks", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.ReportService.ResponseOfDataTable> GetMostBorrowedBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOverdueBooks", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LibrarySystem.App.ReportService.ResponseOfDataTable GetOverdueBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOverdueBooks", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.ReportService.ResponseOfDataTable> GetOverdueBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBorrowedBooksByCategory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LibrarySystem.App.ReportService.ResponseOfDataTable GetBorrowedBooksByCategory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBorrowedBooksByCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.ReportService.ResponseOfDataTable> GetBorrowedBooksByCategoryAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResponseOfDataTable : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string messageField;
        
        private System.Data.DataTable dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Data.DataTable Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReportSoapServiceSoapChannel : LibrarySystem.App.ReportService.ReportSoapServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportSoapServiceSoapClient : System.ServiceModel.ClientBase<LibrarySystem.App.ReportService.ReportSoapServiceSoap>, LibrarySystem.App.ReportService.ReportSoapServiceSoap {
        
        public ReportSoapServiceSoapClient() {
        }
        
        public ReportSoapServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportSoapServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportSoapServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportSoapServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LibrarySystem.App.ReportService.ResponseOfDataTable GetMostBorrowedBooks() {
            return base.Channel.GetMostBorrowedBooks();
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.ReportService.ResponseOfDataTable> GetMostBorrowedBooksAsync() {
            return base.Channel.GetMostBorrowedBooksAsync();
        }
        
        public LibrarySystem.App.ReportService.ResponseOfDataTable GetOverdueBooks() {
            return base.Channel.GetOverdueBooks();
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.ReportService.ResponseOfDataTable> GetOverdueBooksAsync() {
            return base.Channel.GetOverdueBooksAsync();
        }
        
        public LibrarySystem.App.ReportService.ResponseOfDataTable GetBorrowedBooksByCategory() {
            return base.Channel.GetBorrowedBooksByCategory();
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.ReportService.ResponseOfDataTable> GetBorrowedBooksByCategoryAsync() {
            return base.Channel.GetBorrowedBooksByCategoryAsync();
        }
    }
}
