//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem.App.AuditService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuditActionType", Namespace="http://tempuri.org/")]
    public enum AuditActionType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ApplicationException = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ApplicationStarted = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ApplicationEnded = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Login = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Logout = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CreateBook = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EditBook = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeleteBook = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SearchBook = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReserveBook = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BorrowBook = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReturnBook = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ViewAvailableBooks = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ViewBorrowedBooks = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GetReportMostBorrowedBooks = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GetReportOverdueBooks = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GetReportBorrowedBooksByCategory = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessUnauthorizedPage = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ManageUsers = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ManageAuthors = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ManageCategories = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ManageLanguages = 22,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfBoolean", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResponseOfBoolean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        private bool DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuditLogDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AuditLogDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> UserIdField;
        
        private LibrarySystem.App.AuditService.AuditActionType ActionTypeField;
        
        private System.DateTime ActionTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public LibrarySystem.App.AuditService.AuditActionType ActionType {
            get {
                return this.ActionTypeField;
            }
            set {
                if ((this.ActionTypeField.Equals(value) != true)) {
                    this.ActionTypeField = value;
                    this.RaisePropertyChanged("ActionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime ActionTime {
            get {
                return this.ActionTimeField;
            }
            set {
                if ((this.ActionTimeField.Equals(value) != true)) {
                    this.ActionTimeField = value;
                    this.RaisePropertyChanged("ActionTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuditService.AuditSoapServiceSoap")]
    public interface AuditSoapServiceSoap {
        
        // CODEGEN: Generating message contract since element name details from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Log", ReplyAction="*")]
        LibrarySystem.App.AuditService.LogResponse Log(LibrarySystem.App.AuditService.LogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Log", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.AuditService.LogResponse> LogAsync(LibrarySystem.App.AuditService.LogRequest request);
        
        // CODEGEN: Generating message contract since element name log from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogWithDto", ReplyAction="*")]
        LibrarySystem.App.AuditService.LogWithDtoResponse LogWithDto(LibrarySystem.App.AuditService.LogWithDtoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogWithDto", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.AuditService.LogWithDtoResponse> LogWithDtoAsync(LibrarySystem.App.AuditService.LogWithDtoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Log", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.AuditService.LogRequestBody Body;
        
        public LogRequest() {
        }
        
        public LogRequest(LibrarySystem.App.AuditService.LogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public LibrarySystem.App.AuditService.AuditActionType actionType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string details;
        
        public LogRequestBody() {
        }
        
        public LogRequestBody(LibrarySystem.App.AuditService.AuditActionType actionType, int userId, string details) {
            this.actionType = actionType;
            this.userId = userId;
            this.details = details;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.AuditService.LogResponseBody Body;
        
        public LogResponse() {
        }
        
        public LogResponse(LibrarySystem.App.AuditService.LogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LibrarySystem.App.AuditService.ResponseOfBoolean LogResult;
        
        public LogResponseBody() {
        }
        
        public LogResponseBody(LibrarySystem.App.AuditService.ResponseOfBoolean LogResult) {
            this.LogResult = LogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogWithDtoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogWithDto", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.AuditService.LogWithDtoRequestBody Body;
        
        public LogWithDtoRequest() {
        }
        
        public LogWithDtoRequest(LibrarySystem.App.AuditService.LogWithDtoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogWithDtoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LibrarySystem.App.AuditService.AuditLogDto log;
        
        public LogWithDtoRequestBody() {
        }
        
        public LogWithDtoRequestBody(LibrarySystem.App.AuditService.AuditLogDto log) {
            this.log = log;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogWithDtoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogWithDtoResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.AuditService.LogWithDtoResponseBody Body;
        
        public LogWithDtoResponse() {
        }
        
        public LogWithDtoResponse(LibrarySystem.App.AuditService.LogWithDtoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogWithDtoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LibrarySystem.App.AuditService.ResponseOfBoolean LogWithDtoResult;
        
        public LogWithDtoResponseBody() {
        }
        
        public LogWithDtoResponseBody(LibrarySystem.App.AuditService.ResponseOfBoolean LogWithDtoResult) {
            this.LogWithDtoResult = LogWithDtoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuditSoapServiceSoapChannel : LibrarySystem.App.AuditService.AuditSoapServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuditSoapServiceSoapClient : System.ServiceModel.ClientBase<LibrarySystem.App.AuditService.AuditSoapServiceSoap>, LibrarySystem.App.AuditService.AuditSoapServiceSoap {
        
        public AuditSoapServiceSoapClient() {
        }
        
        public AuditSoapServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuditSoapServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuditSoapServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuditSoapServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibrarySystem.App.AuditService.LogResponse LibrarySystem.App.AuditService.AuditSoapServiceSoap.Log(LibrarySystem.App.AuditService.LogRequest request) {
            return base.Channel.Log(request);
        }
        
        public LibrarySystem.App.AuditService.ResponseOfBoolean Log(LibrarySystem.App.AuditService.AuditActionType actionType, int userId, string details) {
            LibrarySystem.App.AuditService.LogRequest inValue = new LibrarySystem.App.AuditService.LogRequest();
            inValue.Body = new LibrarySystem.App.AuditService.LogRequestBody();
            inValue.Body.actionType = actionType;
            inValue.Body.userId = userId;
            inValue.Body.details = details;
            LibrarySystem.App.AuditService.LogResponse retVal = ((LibrarySystem.App.AuditService.AuditSoapServiceSoap)(this)).Log(inValue);
            return retVal.Body.LogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySystem.App.AuditService.LogResponse> LibrarySystem.App.AuditService.AuditSoapServiceSoap.LogAsync(LibrarySystem.App.AuditService.LogRequest request) {
            return base.Channel.LogAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.AuditService.LogResponse> LogAsync(LibrarySystem.App.AuditService.AuditActionType actionType, int userId, string details) {
            LibrarySystem.App.AuditService.LogRequest inValue = new LibrarySystem.App.AuditService.LogRequest();
            inValue.Body = new LibrarySystem.App.AuditService.LogRequestBody();
            inValue.Body.actionType = actionType;
            inValue.Body.userId = userId;
            inValue.Body.details = details;
            return ((LibrarySystem.App.AuditService.AuditSoapServiceSoap)(this)).LogAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibrarySystem.App.AuditService.LogWithDtoResponse LibrarySystem.App.AuditService.AuditSoapServiceSoap.LogWithDto(LibrarySystem.App.AuditService.LogWithDtoRequest request) {
            return base.Channel.LogWithDto(request);
        }
        
        public LibrarySystem.App.AuditService.ResponseOfBoolean LogWithDto(LibrarySystem.App.AuditService.AuditLogDto log) {
            LibrarySystem.App.AuditService.LogWithDtoRequest inValue = new LibrarySystem.App.AuditService.LogWithDtoRequest();
            inValue.Body = new LibrarySystem.App.AuditService.LogWithDtoRequestBody();
            inValue.Body.log = log;
            LibrarySystem.App.AuditService.LogWithDtoResponse retVal = ((LibrarySystem.App.AuditService.AuditSoapServiceSoap)(this)).LogWithDto(inValue);
            return retVal.Body.LogWithDtoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySystem.App.AuditService.LogWithDtoResponse> LibrarySystem.App.AuditService.AuditSoapServiceSoap.LogWithDtoAsync(LibrarySystem.App.AuditService.LogWithDtoRequest request) {
            return base.Channel.LogWithDtoAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.AuditService.LogWithDtoResponse> LogWithDtoAsync(LibrarySystem.App.AuditService.AuditLogDto log) {
            LibrarySystem.App.AuditService.LogWithDtoRequest inValue = new LibrarySystem.App.AuditService.LogWithDtoRequest();
            inValue.Body = new LibrarySystem.App.AuditService.LogWithDtoRequestBody();
            inValue.Body.log = log;
            return ((LibrarySystem.App.AuditService.AuditSoapServiceSoap)(this)).LogWithDtoAsync(inValue);
        }
    }
}
