//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem.App.BookReservationService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookReservationService.BookReservationSoapServiceSoap")]
    public interface BookReservationSoapServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Reserve", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LibrarySystem.App.BookReservationService.ResponseOfReserveViewDto Reserve(LibrarySystem.App.BookReservationService.ReserveCreateDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Reserve", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.BookReservationService.ResponseOfReserveViewDto> ReserveAsync(LibrarySystem.App.BookReservationService.ReserveCreateDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateReservation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LibrarySystem.App.BookReservationService.ResponseOfReserveViewDto UpdateReservation(LibrarySystem.App.BookReservationService.ReserveUpdateDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateReservation", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.BookReservationService.ResponseOfReserveViewDto> UpdateReservationAsync(LibrarySystem.App.BookReservationService.ReserveUpdateDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LibrarySystem.App.BookReservationService.ResponseOfReserveViewDto GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetById", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.BookReservationService.ResponseOfReserveViewDto> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LibrarySystem.App.BookReservationService.ResponseOfDataTable GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.BookReservationService.ResponseOfDataTable> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllByUserId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LibrarySystem.App.BookReservationService.ResponseOfDataTable GetAllByUserId(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllByUserId", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.BookReservationService.ResponseOfDataTable> GetAllByUserIdAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelReservation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LibrarySystem.App.BookReservationService.ResponseOfBoolean CancelReservation(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelReservation", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.BookReservationService.ResponseOfBoolean> CancelReservationAsync(int id);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReserveCreateDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int uIDField;
        
        private string iSBNField;
        
        private System.DateTime reservedDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int UID {
            get {
                return this.uIDField;
            }
            set {
                this.uIDField = value;
                this.RaisePropertyChanged("UID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ISBN {
            get {
                return this.iSBNField;
            }
            set {
                this.iSBNField = value;
                this.RaisePropertyChanged("ISBN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ReservedDate {
            get {
                return this.reservedDateField;
            }
            set {
                this.reservedDateField = value;
                this.RaisePropertyChanged("ReservedDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResponseOfBoolean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string messageField;
        
        private bool dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResponseOfDataTable : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string messageField;
        
        private System.Data.DataTable dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Data.DataTable Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReserveUpdateDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int rIDField;
        
        private string iSBNField;
        
        private System.DateTime reservedDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int RID {
            get {
                return this.rIDField;
            }
            set {
                this.rIDField = value;
                this.RaisePropertyChanged("RID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ISBN {
            get {
                return this.iSBNField;
            }
            set {
                this.iSBNField = value;
                this.RaisePropertyChanged("ISBN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ReservedDate {
            get {
                return this.reservedDateField;
            }
            set {
                this.reservedDateField = value;
                this.RaisePropertyChanged("ReservedDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReserveViewDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int rIDField;
        
        private string iSBNField;
        
        private System.DateTime reservedDateField;
        
        private string bookNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int RID {
            get {
                return this.rIDField;
            }
            set {
                this.rIDField = value;
                this.RaisePropertyChanged("RID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ISBN {
            get {
                return this.iSBNField;
            }
            set {
                this.iSBNField = value;
                this.RaisePropertyChanged("ISBN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ReservedDate {
            get {
                return this.reservedDateField;
            }
            set {
                this.reservedDateField = value;
                this.RaisePropertyChanged("ReservedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BookName {
            get {
                return this.bookNameField;
            }
            set {
                this.bookNameField = value;
                this.RaisePropertyChanged("BookName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResponseOfReserveViewDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string messageField;
        
        private ReserveViewDto dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ReserveViewDto Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BookReservationSoapServiceSoapChannel : LibrarySystem.App.BookReservationService.BookReservationSoapServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookReservationSoapServiceSoapClient : System.ServiceModel.ClientBase<LibrarySystem.App.BookReservationService.BookReservationSoapServiceSoap>, LibrarySystem.App.BookReservationService.BookReservationSoapServiceSoap {
        
        public BookReservationSoapServiceSoapClient() {
        }
        
        public BookReservationSoapServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookReservationSoapServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookReservationSoapServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookReservationSoapServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LibrarySystem.App.BookReservationService.ResponseOfReserveViewDto Reserve(LibrarySystem.App.BookReservationService.ReserveCreateDto dto) {
            return base.Channel.Reserve(dto);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.BookReservationService.ResponseOfReserveViewDto> ReserveAsync(LibrarySystem.App.BookReservationService.ReserveCreateDto dto) {
            return base.Channel.ReserveAsync(dto);
        }
        
        public LibrarySystem.App.BookReservationService.ResponseOfReserveViewDto UpdateReservation(LibrarySystem.App.BookReservationService.ReserveUpdateDto dto) {
            return base.Channel.UpdateReservation(dto);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.BookReservationService.ResponseOfReserveViewDto> UpdateReservationAsync(LibrarySystem.App.BookReservationService.ReserveUpdateDto dto) {
            return base.Channel.UpdateReservationAsync(dto);
        }
        
        public LibrarySystem.App.BookReservationService.ResponseOfReserveViewDto GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.BookReservationService.ResponseOfReserveViewDto> GetByIdAsync(int id) {
            return base.Channel.GetByIdAsync(id);
        }
        
        public LibrarySystem.App.BookReservationService.ResponseOfDataTable GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.BookReservationService.ResponseOfDataTable> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public LibrarySystem.App.BookReservationService.ResponseOfDataTable GetAllByUserId(int userId) {
            return base.Channel.GetAllByUserId(userId);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.BookReservationService.ResponseOfDataTable> GetAllByUserIdAsync(int userId) {
            return base.Channel.GetAllByUserIdAsync(userId);
        }
        
        public LibrarySystem.App.BookReservationService.ResponseOfBoolean CancelReservation(int id) {
            return base.Channel.CancelReservation(id);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.BookReservationService.ResponseOfBoolean> CancelReservationAsync(int id) {
            return base.Channel.CancelReservationAsync(id);
        }
    }
}
