version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    user: root
    networks:
      - backend
    volumes:
      - ./init:/init
      - mssql_data:/var/opt/mssql
    entrypoint: ["/bin/bash", "-c", "chmod +x /init/entrypoint.sh && /init/entrypoint.sh"]
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -U sa -P $${MSSQL_SA_PASSWORD} -Q 'SELECT 1' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 30  # 30 retries × 5s = 150s total wait time

volumes:
  mssql_data:
    driver: local

networks:
  backend:
    driver: bridge