//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem.App.TestService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TestService.TestSoapServiceSoap")]
    public interface TestSoapServiceSoap {
        
        // CODEGEN: Generating message contract since element name SoapServiceHealthCheckResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SoapServiceHealthCheck", ReplyAction="*")]
        LibrarySystem.App.TestService.SoapServiceHealthCheckResponse SoapServiceHealthCheck(LibrarySystem.App.TestService.SoapServiceHealthCheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SoapServiceHealthCheck", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.TestService.SoapServiceHealthCheckResponse> SoapServiceHealthCheckAsync(LibrarySystem.App.TestService.SoapServiceHealthCheckRequest request);
        
        // CODEGEN: Generating message contract since element name TestDatabaseHealthCheckResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestDatabaseHealthCheck", ReplyAction="*")]
        LibrarySystem.App.TestService.TestDatabaseHealthCheckResponse TestDatabaseHealthCheck(LibrarySystem.App.TestService.TestDatabaseHealthCheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestDatabaseHealthCheck", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestDatabaseHealthCheckResponse> TestDatabaseHealthCheckAsync(LibrarySystem.App.TestService.TestDatabaseHealthCheckRequest request);
        
        // CODEGEN: Generating message contract since element name TestBadRequestExceptionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestBadRequestException", ReplyAction="*")]
        LibrarySystem.App.TestService.TestBadRequestExceptionResponse TestBadRequestException(LibrarySystem.App.TestService.TestBadRequestExceptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestBadRequestException", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestBadRequestExceptionResponse> TestBadRequestExceptionAsync(LibrarySystem.App.TestService.TestBadRequestExceptionRequest request);
        
        // CODEGEN: Generating message contract since element name TestConflictExceptionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestConflictException", ReplyAction="*")]
        LibrarySystem.App.TestService.TestConflictExceptionResponse TestConflictException(LibrarySystem.App.TestService.TestConflictExceptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestConflictException", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestConflictExceptionResponse> TestConflictExceptionAsync(LibrarySystem.App.TestService.TestConflictExceptionRequest request);
        
        // CODEGEN: Generating message contract since element name TestCustomExceptionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestCustomException", ReplyAction="*")]
        LibrarySystem.App.TestService.TestCustomExceptionResponse TestCustomException(LibrarySystem.App.TestService.TestCustomExceptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestCustomException", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestCustomExceptionResponse> TestCustomExceptionAsync(LibrarySystem.App.TestService.TestCustomExceptionRequest request);
        
        // CODEGEN: Generating message contract since element name TestExternalServiceExceptionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestExternalServiceException", ReplyAction="*")]
        LibrarySystem.App.TestService.TestExternalServiceExceptionResponse TestExternalServiceException(LibrarySystem.App.TestService.TestExternalServiceExceptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestExternalServiceException", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestExternalServiceExceptionResponse> TestExternalServiceExceptionAsync(LibrarySystem.App.TestService.TestExternalServiceExceptionRequest request);
        
        // CODEGEN: Generating message contract since element name TestForbiddenExceptionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestForbiddenException", ReplyAction="*")]
        LibrarySystem.App.TestService.TestForbiddenExceptionResponse TestForbiddenException(LibrarySystem.App.TestService.TestForbiddenExceptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestForbiddenException", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestForbiddenExceptionResponse> TestForbiddenExceptionAsync(LibrarySystem.App.TestService.TestForbiddenExceptionRequest request);
        
        // CODEGEN: Generating message contract since element name TestInternalServerErrorExceptionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestInternalServerErrorException", ReplyAction="*")]
        LibrarySystem.App.TestService.TestInternalServerErrorExceptionResponse TestInternalServerErrorException(LibrarySystem.App.TestService.TestInternalServerErrorExceptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestInternalServerErrorException", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestInternalServerErrorExceptionResponse> TestInternalServerErrorExceptionAsync(LibrarySystem.App.TestService.TestInternalServerErrorExceptionRequest request);
        
        // CODEGEN: Generating message contract since element name TestMethodNotAllowedExceptionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestMethodNotAllowedException", ReplyAction="*")]
        LibrarySystem.App.TestService.TestMethodNotAllowedExceptionResponse TestMethodNotAllowedException(LibrarySystem.App.TestService.TestMethodNotAllowedExceptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestMethodNotAllowedException", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestMethodNotAllowedExceptionResponse> TestMethodNotAllowedExceptionAsync(LibrarySystem.App.TestService.TestMethodNotAllowedExceptionRequest request);
        
        // CODEGEN: Generating message contract since element name TestNotFoundExceptionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestNotFoundException", ReplyAction="*")]
        LibrarySystem.App.TestService.TestNotFoundExceptionResponse TestNotFoundException(LibrarySystem.App.TestService.TestNotFoundExceptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestNotFoundException", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestNotFoundExceptionResponse> TestNotFoundExceptionAsync(LibrarySystem.App.TestService.TestNotFoundExceptionRequest request);
        
        // CODEGEN: Generating message contract since element name TestResourceAlreadyExistsExceptionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestResourceAlreadyExistsException", ReplyAction="*")]
        LibrarySystem.App.TestService.TestResourceAlreadyExistsExceptionResponse TestResourceAlreadyExistsException(LibrarySystem.App.TestService.TestResourceAlreadyExistsExceptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestResourceAlreadyExistsException", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestResourceAlreadyExistsExceptionResponse> TestResourceAlreadyExistsExceptionAsync(LibrarySystem.App.TestService.TestResourceAlreadyExistsExceptionRequest request);
        
        // CODEGEN: Generating message contract since element name TestUnauthorizedExceptionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestUnauthorizedException", ReplyAction="*")]
        LibrarySystem.App.TestService.TestUnauthorizedExceptionResponse TestUnauthorizedException(LibrarySystem.App.TestService.TestUnauthorizedExceptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestUnauthorizedException", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestUnauthorizedExceptionResponse> TestUnauthorizedExceptionAsync(LibrarySystem.App.TestService.TestUnauthorizedExceptionRequest request);
        
        // CODEGEN: Generating message contract since element name TestUnprocessableEntityExceptionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestUnprocessableEntityException", ReplyAction="*")]
        LibrarySystem.App.TestService.TestUnprocessableEntityExceptionResponse TestUnprocessableEntityException(LibrarySystem.App.TestService.TestUnprocessableEntityExceptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestUnprocessableEntityException", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestUnprocessableEntityExceptionResponse> TestUnprocessableEntityExceptionAsync(LibrarySystem.App.TestService.TestUnprocessableEntityExceptionRequest request);
        
        // CODEGEN: Generating message contract since element name TestValidationExceptionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestValidationException", ReplyAction="*")]
        LibrarySystem.App.TestService.TestValidationExceptionResponse TestValidationException(LibrarySystem.App.TestService.TestValidationExceptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestValidationException", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestValidationExceptionResponse> TestValidationExceptionAsync(LibrarySystem.App.TestService.TestValidationExceptionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SoapServiceHealthCheckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SoapServiceHealthCheck", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.TestService.SoapServiceHealthCheckRequestBody Body;
        
        public SoapServiceHealthCheckRequest() {
        }
        
        public SoapServiceHealthCheckRequest(LibrarySystem.App.TestService.SoapServiceHealthCheckRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SoapServiceHealthCheckRequestBody {
        
        public SoapServiceHealthCheckRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SoapServiceHealthCheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SoapServiceHealthCheckResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.TestService.SoapServiceHealthCheckResponseBody Body;
        
        public SoapServiceHealthCheckResponse() {
        }
        
        public SoapServiceHealthCheckResponse(LibrarySystem.App.TestService.SoapServiceHealthCheckResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SoapServiceHealthCheckResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SoapServiceHealthCheckResult;
        
        public SoapServiceHealthCheckResponseBody() {
        }
        
        public SoapServiceHealthCheckResponseBody(string SoapServiceHealthCheckResult) {
            this.SoapServiceHealthCheckResult = SoapServiceHealthCheckResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestDatabaseHealthCheckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestDatabaseHealthCheck", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.TestService.TestDatabaseHealthCheckRequestBody Body;
        
        public TestDatabaseHealthCheckRequest() {
        }
        
        public TestDatabaseHealthCheckRequest(LibrarySystem.App.TestService.TestDatabaseHealthCheckRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestDatabaseHealthCheckRequestBody {
        
        public TestDatabaseHealthCheckRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestDatabaseHealthCheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestDatabaseHealthCheckResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.TestService.TestDatabaseHealthCheckResponseBody Body;
        
        public TestDatabaseHealthCheckResponse() {
        }
        
        public TestDatabaseHealthCheckResponse(LibrarySystem.App.TestService.TestDatabaseHealthCheckResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestDatabaseHealthCheckResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestDatabaseHealthCheckResult;
        
        public TestDatabaseHealthCheckResponseBody() {
        }
        
        public TestDatabaseHealthCheckResponseBody(string TestDatabaseHealthCheckResult) {
            this.TestDatabaseHealthCheckResult = TestDatabaseHealthCheckResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestBadRequestExceptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestBadRequestException", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.TestService.TestBadRequestExceptionRequestBody Body;
        
        public TestBadRequestExceptionRequest() {
        }
        
        public TestBadRequestExceptionRequest(LibrarySystem.App.TestService.TestBadRequestExceptionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestBadRequestExceptionRequestBody {
        
        public TestBadRequestExceptionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestBadRequestExceptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestBadRequestExceptionResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.TestService.TestBadRequestExceptionResponseBody Body;
        
        public TestBadRequestExceptionResponse() {
        }
        
        public TestBadRequestExceptionResponse(LibrarySystem.App.TestService.TestBadRequestExceptionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestBadRequestExceptionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestBadRequestExceptionResult;
        
        public TestBadRequestExceptionResponseBody() {
        }
        
        public TestBadRequestExceptionResponseBody(string TestBadRequestExceptionResult) {
            this.TestBadRequestExceptionResult = TestBadRequestExceptionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestConflictExceptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestConflictException", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.TestService.TestConflictExceptionRequestBody Body;
        
        public TestConflictExceptionRequest() {
        }
        
        public TestConflictExceptionRequest(LibrarySystem.App.TestService.TestConflictExceptionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestConflictExceptionRequestBody {
        
        public TestConflictExceptionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestConflictExceptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestConflictExceptionResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.TestService.TestConflictExceptionResponseBody Body;
        
        public TestConflictExceptionResponse() {
        }
        
        public TestConflictExceptionResponse(LibrarySystem.App.TestService.TestConflictExceptionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestConflictExceptionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestConflictExceptionResult;
        
        public TestConflictExceptionResponseBody() {
        }
        
        public TestConflictExceptionResponseBody(string TestConflictExceptionResult) {
            this.TestConflictExceptionResult = TestConflictExceptionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestCustomExceptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestCustomException", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.TestService.TestCustomExceptionRequestBody Body;
        
        public TestCustomExceptionRequest() {
        }
        
        public TestCustomExceptionRequest(LibrarySystem.App.TestService.TestCustomExceptionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestCustomExceptionRequestBody {
        
        public TestCustomExceptionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestCustomExceptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestCustomExceptionResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.TestService.TestCustomExceptionResponseBody Body;
        
        public TestCustomExceptionResponse() {
        }
        
        public TestCustomExceptionResponse(LibrarySystem.App.TestService.TestCustomExceptionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestCustomExceptionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestCustomExceptionResult;
        
        public TestCustomExceptionResponseBody() {
        }
        
        public TestCustomExceptionResponseBody(string TestCustomExceptionResult) {
            this.TestCustomExceptionResult = TestCustomExceptionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestExternalServiceExceptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestExternalServiceException", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.TestService.TestExternalServiceExceptionRequestBody Body;
        
        public TestExternalServiceExceptionRequest() {
        }
        
        public TestExternalServiceExceptionRequest(LibrarySystem.App.TestService.TestExternalServiceExceptionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestExternalServiceExceptionRequestBody {
        
        public TestExternalServiceExceptionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestExternalServiceExceptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestExternalServiceExceptionResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.TestService.TestExternalServiceExceptionResponseBody Body;
        
        public TestExternalServiceExceptionResponse() {
        }
        
        public TestExternalServiceExceptionResponse(LibrarySystem.App.TestService.TestExternalServiceExceptionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestExternalServiceExceptionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestExternalServiceExceptionResult;
        
        public TestExternalServiceExceptionResponseBody() {
        }
        
        public TestExternalServiceExceptionResponseBody(string TestExternalServiceExceptionResult) {
            this.TestExternalServiceExceptionResult = TestExternalServiceExceptionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestForbiddenExceptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestForbiddenException", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.TestService.TestForbiddenExceptionRequestBody Body;
        
        public TestForbiddenExceptionRequest() {
        }
        
        public TestForbiddenExceptionRequest(LibrarySystem.App.TestService.TestForbiddenExceptionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestForbiddenExceptionRequestBody {
        
        public TestForbiddenExceptionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestForbiddenExceptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestForbiddenExceptionResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.TestService.TestForbiddenExceptionResponseBody Body;
        
        public TestForbiddenExceptionResponse() {
        }
        
        public TestForbiddenExceptionResponse(LibrarySystem.App.TestService.TestForbiddenExceptionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestForbiddenExceptionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestForbiddenExceptionResult;
        
        public TestForbiddenExceptionResponseBody() {
        }
        
        public TestForbiddenExceptionResponseBody(string TestForbiddenExceptionResult) {
            this.TestForbiddenExceptionResult = TestForbiddenExceptionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestInternalServerErrorExceptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestInternalServerErrorException", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.TestService.TestInternalServerErrorExceptionRequestBody Body;
        
        public TestInternalServerErrorExceptionRequest() {
        }
        
        public TestInternalServerErrorExceptionRequest(LibrarySystem.App.TestService.TestInternalServerErrorExceptionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestInternalServerErrorExceptionRequestBody {
        
        public TestInternalServerErrorExceptionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestInternalServerErrorExceptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestInternalServerErrorExceptionResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.TestService.TestInternalServerErrorExceptionResponseBody Body;
        
        public TestInternalServerErrorExceptionResponse() {
        }
        
        public TestInternalServerErrorExceptionResponse(LibrarySystem.App.TestService.TestInternalServerErrorExceptionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestInternalServerErrorExceptionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestInternalServerErrorExceptionResult;
        
        public TestInternalServerErrorExceptionResponseBody() {
        }
        
        public TestInternalServerErrorExceptionResponseBody(string TestInternalServerErrorExceptionResult) {
            this.TestInternalServerErrorExceptionResult = TestInternalServerErrorExceptionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestMethodNotAllowedExceptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestMethodNotAllowedException", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.TestService.TestMethodNotAllowedExceptionRequestBody Body;
        
        public TestMethodNotAllowedExceptionRequest() {
        }
        
        public TestMethodNotAllowedExceptionRequest(LibrarySystem.App.TestService.TestMethodNotAllowedExceptionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestMethodNotAllowedExceptionRequestBody {
        
        public TestMethodNotAllowedExceptionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestMethodNotAllowedExceptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestMethodNotAllowedExceptionResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.TestService.TestMethodNotAllowedExceptionResponseBody Body;
        
        public TestMethodNotAllowedExceptionResponse() {
        }
        
        public TestMethodNotAllowedExceptionResponse(LibrarySystem.App.TestService.TestMethodNotAllowedExceptionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestMethodNotAllowedExceptionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestMethodNotAllowedExceptionResult;
        
        public TestMethodNotAllowedExceptionResponseBody() {
        }
        
        public TestMethodNotAllowedExceptionResponseBody(string TestMethodNotAllowedExceptionResult) {
            this.TestMethodNotAllowedExceptionResult = TestMethodNotAllowedExceptionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestNotFoundExceptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestNotFoundException", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.TestService.TestNotFoundExceptionRequestBody Body;
        
        public TestNotFoundExceptionRequest() {
        }
        
        public TestNotFoundExceptionRequest(LibrarySystem.App.TestService.TestNotFoundExceptionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestNotFoundExceptionRequestBody {
        
        public TestNotFoundExceptionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestNotFoundExceptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestNotFoundExceptionResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.TestService.TestNotFoundExceptionResponseBody Body;
        
        public TestNotFoundExceptionResponse() {
        }
        
        public TestNotFoundExceptionResponse(LibrarySystem.App.TestService.TestNotFoundExceptionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestNotFoundExceptionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestNotFoundExceptionResult;
        
        public TestNotFoundExceptionResponseBody() {
        }
        
        public TestNotFoundExceptionResponseBody(string TestNotFoundExceptionResult) {
            this.TestNotFoundExceptionResult = TestNotFoundExceptionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestResourceAlreadyExistsExceptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestResourceAlreadyExistsException", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.TestService.TestResourceAlreadyExistsExceptionRequestBody Body;
        
        public TestResourceAlreadyExistsExceptionRequest() {
        }
        
        public TestResourceAlreadyExistsExceptionRequest(LibrarySystem.App.TestService.TestResourceAlreadyExistsExceptionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestResourceAlreadyExistsExceptionRequestBody {
        
        public TestResourceAlreadyExistsExceptionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestResourceAlreadyExistsExceptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestResourceAlreadyExistsExceptionResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.TestService.TestResourceAlreadyExistsExceptionResponseBody Body;
        
        public TestResourceAlreadyExistsExceptionResponse() {
        }
        
        public TestResourceAlreadyExistsExceptionResponse(LibrarySystem.App.TestService.TestResourceAlreadyExistsExceptionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestResourceAlreadyExistsExceptionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestResourceAlreadyExistsExceptionResult;
        
        public TestResourceAlreadyExistsExceptionResponseBody() {
        }
        
        public TestResourceAlreadyExistsExceptionResponseBody(string TestResourceAlreadyExistsExceptionResult) {
            this.TestResourceAlreadyExistsExceptionResult = TestResourceAlreadyExistsExceptionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestUnauthorizedExceptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestUnauthorizedException", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.TestService.TestUnauthorizedExceptionRequestBody Body;
        
        public TestUnauthorizedExceptionRequest() {
        }
        
        public TestUnauthorizedExceptionRequest(LibrarySystem.App.TestService.TestUnauthorizedExceptionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestUnauthorizedExceptionRequestBody {
        
        public TestUnauthorizedExceptionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestUnauthorizedExceptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestUnauthorizedExceptionResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.TestService.TestUnauthorizedExceptionResponseBody Body;
        
        public TestUnauthorizedExceptionResponse() {
        }
        
        public TestUnauthorizedExceptionResponse(LibrarySystem.App.TestService.TestUnauthorizedExceptionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestUnauthorizedExceptionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestUnauthorizedExceptionResult;
        
        public TestUnauthorizedExceptionResponseBody() {
        }
        
        public TestUnauthorizedExceptionResponseBody(string TestUnauthorizedExceptionResult) {
            this.TestUnauthorizedExceptionResult = TestUnauthorizedExceptionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestUnprocessableEntityExceptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestUnprocessableEntityException", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.TestService.TestUnprocessableEntityExceptionRequestBody Body;
        
        public TestUnprocessableEntityExceptionRequest() {
        }
        
        public TestUnprocessableEntityExceptionRequest(LibrarySystem.App.TestService.TestUnprocessableEntityExceptionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestUnprocessableEntityExceptionRequestBody {
        
        public TestUnprocessableEntityExceptionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestUnprocessableEntityExceptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestUnprocessableEntityExceptionResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.TestService.TestUnprocessableEntityExceptionResponseBody Body;
        
        public TestUnprocessableEntityExceptionResponse() {
        }
        
        public TestUnprocessableEntityExceptionResponse(LibrarySystem.App.TestService.TestUnprocessableEntityExceptionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestUnprocessableEntityExceptionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestUnprocessableEntityExceptionResult;
        
        public TestUnprocessableEntityExceptionResponseBody() {
        }
        
        public TestUnprocessableEntityExceptionResponseBody(string TestUnprocessableEntityExceptionResult) {
            this.TestUnprocessableEntityExceptionResult = TestUnprocessableEntityExceptionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestValidationExceptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestValidationException", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.TestService.TestValidationExceptionRequestBody Body;
        
        public TestValidationExceptionRequest() {
        }
        
        public TestValidationExceptionRequest(LibrarySystem.App.TestService.TestValidationExceptionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestValidationExceptionRequestBody {
        
        public TestValidationExceptionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestValidationExceptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestValidationExceptionResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.TestService.TestValidationExceptionResponseBody Body;
        
        public TestValidationExceptionResponse() {
        }
        
        public TestValidationExceptionResponse(LibrarySystem.App.TestService.TestValidationExceptionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestValidationExceptionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestValidationExceptionResult;
        
        public TestValidationExceptionResponseBody() {
        }
        
        public TestValidationExceptionResponseBody(string TestValidationExceptionResult) {
            this.TestValidationExceptionResult = TestValidationExceptionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TestSoapServiceSoapChannel : LibrarySystem.App.TestService.TestSoapServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestSoapServiceSoapClient : System.ServiceModel.ClientBase<LibrarySystem.App.TestService.TestSoapServiceSoap>, LibrarySystem.App.TestService.TestSoapServiceSoap {
        
        public TestSoapServiceSoapClient() {
        }
        
        public TestSoapServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestSoapServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestSoapServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestSoapServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibrarySystem.App.TestService.SoapServiceHealthCheckResponse LibrarySystem.App.TestService.TestSoapServiceSoap.SoapServiceHealthCheck(LibrarySystem.App.TestService.SoapServiceHealthCheckRequest request) {
            return base.Channel.SoapServiceHealthCheck(request);
        }
        
        public string SoapServiceHealthCheck() {
            LibrarySystem.App.TestService.SoapServiceHealthCheckRequest inValue = new LibrarySystem.App.TestService.SoapServiceHealthCheckRequest();
            inValue.Body = new LibrarySystem.App.TestService.SoapServiceHealthCheckRequestBody();
            LibrarySystem.App.TestService.SoapServiceHealthCheckResponse retVal = ((LibrarySystem.App.TestService.TestSoapServiceSoap)(this)).SoapServiceHealthCheck(inValue);
            return retVal.Body.SoapServiceHealthCheckResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySystem.App.TestService.SoapServiceHealthCheckResponse> LibrarySystem.App.TestService.TestSoapServiceSoap.SoapServiceHealthCheckAsync(LibrarySystem.App.TestService.SoapServiceHealthCheckRequest request) {
            return base.Channel.SoapServiceHealthCheckAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.TestService.SoapServiceHealthCheckResponse> SoapServiceHealthCheckAsync() {
            LibrarySystem.App.TestService.SoapServiceHealthCheckRequest inValue = new LibrarySystem.App.TestService.SoapServiceHealthCheckRequest();
            inValue.Body = new LibrarySystem.App.TestService.SoapServiceHealthCheckRequestBody();
            return ((LibrarySystem.App.TestService.TestSoapServiceSoap)(this)).SoapServiceHealthCheckAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibrarySystem.App.TestService.TestDatabaseHealthCheckResponse LibrarySystem.App.TestService.TestSoapServiceSoap.TestDatabaseHealthCheck(LibrarySystem.App.TestService.TestDatabaseHealthCheckRequest request) {
            return base.Channel.TestDatabaseHealthCheck(request);
        }
        
        public string TestDatabaseHealthCheck() {
            LibrarySystem.App.TestService.TestDatabaseHealthCheckRequest inValue = new LibrarySystem.App.TestService.TestDatabaseHealthCheckRequest();
            inValue.Body = new LibrarySystem.App.TestService.TestDatabaseHealthCheckRequestBody();
            LibrarySystem.App.TestService.TestDatabaseHealthCheckResponse retVal = ((LibrarySystem.App.TestService.TestSoapServiceSoap)(this)).TestDatabaseHealthCheck(inValue);
            return retVal.Body.TestDatabaseHealthCheckResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestDatabaseHealthCheckResponse> LibrarySystem.App.TestService.TestSoapServiceSoap.TestDatabaseHealthCheckAsync(LibrarySystem.App.TestService.TestDatabaseHealthCheckRequest request) {
            return base.Channel.TestDatabaseHealthCheckAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestDatabaseHealthCheckResponse> TestDatabaseHealthCheckAsync() {
            LibrarySystem.App.TestService.TestDatabaseHealthCheckRequest inValue = new LibrarySystem.App.TestService.TestDatabaseHealthCheckRequest();
            inValue.Body = new LibrarySystem.App.TestService.TestDatabaseHealthCheckRequestBody();
            return ((LibrarySystem.App.TestService.TestSoapServiceSoap)(this)).TestDatabaseHealthCheckAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibrarySystem.App.TestService.TestBadRequestExceptionResponse LibrarySystem.App.TestService.TestSoapServiceSoap.TestBadRequestException(LibrarySystem.App.TestService.TestBadRequestExceptionRequest request) {
            return base.Channel.TestBadRequestException(request);
        }
        
        public string TestBadRequestException() {
            LibrarySystem.App.TestService.TestBadRequestExceptionRequest inValue = new LibrarySystem.App.TestService.TestBadRequestExceptionRequest();
            inValue.Body = new LibrarySystem.App.TestService.TestBadRequestExceptionRequestBody();
            LibrarySystem.App.TestService.TestBadRequestExceptionResponse retVal = ((LibrarySystem.App.TestService.TestSoapServiceSoap)(this)).TestBadRequestException(inValue);
            return retVal.Body.TestBadRequestExceptionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestBadRequestExceptionResponse> LibrarySystem.App.TestService.TestSoapServiceSoap.TestBadRequestExceptionAsync(LibrarySystem.App.TestService.TestBadRequestExceptionRequest request) {
            return base.Channel.TestBadRequestExceptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestBadRequestExceptionResponse> TestBadRequestExceptionAsync() {
            LibrarySystem.App.TestService.TestBadRequestExceptionRequest inValue = new LibrarySystem.App.TestService.TestBadRequestExceptionRequest();
            inValue.Body = new LibrarySystem.App.TestService.TestBadRequestExceptionRequestBody();
            return ((LibrarySystem.App.TestService.TestSoapServiceSoap)(this)).TestBadRequestExceptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibrarySystem.App.TestService.TestConflictExceptionResponse LibrarySystem.App.TestService.TestSoapServiceSoap.TestConflictException(LibrarySystem.App.TestService.TestConflictExceptionRequest request) {
            return base.Channel.TestConflictException(request);
        }
        
        public string TestConflictException() {
            LibrarySystem.App.TestService.TestConflictExceptionRequest inValue = new LibrarySystem.App.TestService.TestConflictExceptionRequest();
            inValue.Body = new LibrarySystem.App.TestService.TestConflictExceptionRequestBody();
            LibrarySystem.App.TestService.TestConflictExceptionResponse retVal = ((LibrarySystem.App.TestService.TestSoapServiceSoap)(this)).TestConflictException(inValue);
            return retVal.Body.TestConflictExceptionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestConflictExceptionResponse> LibrarySystem.App.TestService.TestSoapServiceSoap.TestConflictExceptionAsync(LibrarySystem.App.TestService.TestConflictExceptionRequest request) {
            return base.Channel.TestConflictExceptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestConflictExceptionResponse> TestConflictExceptionAsync() {
            LibrarySystem.App.TestService.TestConflictExceptionRequest inValue = new LibrarySystem.App.TestService.TestConflictExceptionRequest();
            inValue.Body = new LibrarySystem.App.TestService.TestConflictExceptionRequestBody();
            return ((LibrarySystem.App.TestService.TestSoapServiceSoap)(this)).TestConflictExceptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibrarySystem.App.TestService.TestCustomExceptionResponse LibrarySystem.App.TestService.TestSoapServiceSoap.TestCustomException(LibrarySystem.App.TestService.TestCustomExceptionRequest request) {
            return base.Channel.TestCustomException(request);
        }
        
        public string TestCustomException() {
            LibrarySystem.App.TestService.TestCustomExceptionRequest inValue = new LibrarySystem.App.TestService.TestCustomExceptionRequest();
            inValue.Body = new LibrarySystem.App.TestService.TestCustomExceptionRequestBody();
            LibrarySystem.App.TestService.TestCustomExceptionResponse retVal = ((LibrarySystem.App.TestService.TestSoapServiceSoap)(this)).TestCustomException(inValue);
            return retVal.Body.TestCustomExceptionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestCustomExceptionResponse> LibrarySystem.App.TestService.TestSoapServiceSoap.TestCustomExceptionAsync(LibrarySystem.App.TestService.TestCustomExceptionRequest request) {
            return base.Channel.TestCustomExceptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestCustomExceptionResponse> TestCustomExceptionAsync() {
            LibrarySystem.App.TestService.TestCustomExceptionRequest inValue = new LibrarySystem.App.TestService.TestCustomExceptionRequest();
            inValue.Body = new LibrarySystem.App.TestService.TestCustomExceptionRequestBody();
            return ((LibrarySystem.App.TestService.TestSoapServiceSoap)(this)).TestCustomExceptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibrarySystem.App.TestService.TestExternalServiceExceptionResponse LibrarySystem.App.TestService.TestSoapServiceSoap.TestExternalServiceException(LibrarySystem.App.TestService.TestExternalServiceExceptionRequest request) {
            return base.Channel.TestExternalServiceException(request);
        }
        
        public string TestExternalServiceException() {
            LibrarySystem.App.TestService.TestExternalServiceExceptionRequest inValue = new LibrarySystem.App.TestService.TestExternalServiceExceptionRequest();
            inValue.Body = new LibrarySystem.App.TestService.TestExternalServiceExceptionRequestBody();
            LibrarySystem.App.TestService.TestExternalServiceExceptionResponse retVal = ((LibrarySystem.App.TestService.TestSoapServiceSoap)(this)).TestExternalServiceException(inValue);
            return retVal.Body.TestExternalServiceExceptionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestExternalServiceExceptionResponse> LibrarySystem.App.TestService.TestSoapServiceSoap.TestExternalServiceExceptionAsync(LibrarySystem.App.TestService.TestExternalServiceExceptionRequest request) {
            return base.Channel.TestExternalServiceExceptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestExternalServiceExceptionResponse> TestExternalServiceExceptionAsync() {
            LibrarySystem.App.TestService.TestExternalServiceExceptionRequest inValue = new LibrarySystem.App.TestService.TestExternalServiceExceptionRequest();
            inValue.Body = new LibrarySystem.App.TestService.TestExternalServiceExceptionRequestBody();
            return ((LibrarySystem.App.TestService.TestSoapServiceSoap)(this)).TestExternalServiceExceptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibrarySystem.App.TestService.TestForbiddenExceptionResponse LibrarySystem.App.TestService.TestSoapServiceSoap.TestForbiddenException(LibrarySystem.App.TestService.TestForbiddenExceptionRequest request) {
            return base.Channel.TestForbiddenException(request);
        }
        
        public string TestForbiddenException() {
            LibrarySystem.App.TestService.TestForbiddenExceptionRequest inValue = new LibrarySystem.App.TestService.TestForbiddenExceptionRequest();
            inValue.Body = new LibrarySystem.App.TestService.TestForbiddenExceptionRequestBody();
            LibrarySystem.App.TestService.TestForbiddenExceptionResponse retVal = ((LibrarySystem.App.TestService.TestSoapServiceSoap)(this)).TestForbiddenException(inValue);
            return retVal.Body.TestForbiddenExceptionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestForbiddenExceptionResponse> LibrarySystem.App.TestService.TestSoapServiceSoap.TestForbiddenExceptionAsync(LibrarySystem.App.TestService.TestForbiddenExceptionRequest request) {
            return base.Channel.TestForbiddenExceptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestForbiddenExceptionResponse> TestForbiddenExceptionAsync() {
            LibrarySystem.App.TestService.TestForbiddenExceptionRequest inValue = new LibrarySystem.App.TestService.TestForbiddenExceptionRequest();
            inValue.Body = new LibrarySystem.App.TestService.TestForbiddenExceptionRequestBody();
            return ((LibrarySystem.App.TestService.TestSoapServiceSoap)(this)).TestForbiddenExceptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibrarySystem.App.TestService.TestInternalServerErrorExceptionResponse LibrarySystem.App.TestService.TestSoapServiceSoap.TestInternalServerErrorException(LibrarySystem.App.TestService.TestInternalServerErrorExceptionRequest request) {
            return base.Channel.TestInternalServerErrorException(request);
        }
        
        public string TestInternalServerErrorException() {
            LibrarySystem.App.TestService.TestInternalServerErrorExceptionRequest inValue = new LibrarySystem.App.TestService.TestInternalServerErrorExceptionRequest();
            inValue.Body = new LibrarySystem.App.TestService.TestInternalServerErrorExceptionRequestBody();
            LibrarySystem.App.TestService.TestInternalServerErrorExceptionResponse retVal = ((LibrarySystem.App.TestService.TestSoapServiceSoap)(this)).TestInternalServerErrorException(inValue);
            return retVal.Body.TestInternalServerErrorExceptionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestInternalServerErrorExceptionResponse> LibrarySystem.App.TestService.TestSoapServiceSoap.TestInternalServerErrorExceptionAsync(LibrarySystem.App.TestService.TestInternalServerErrorExceptionRequest request) {
            return base.Channel.TestInternalServerErrorExceptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestInternalServerErrorExceptionResponse> TestInternalServerErrorExceptionAsync() {
            LibrarySystem.App.TestService.TestInternalServerErrorExceptionRequest inValue = new LibrarySystem.App.TestService.TestInternalServerErrorExceptionRequest();
            inValue.Body = new LibrarySystem.App.TestService.TestInternalServerErrorExceptionRequestBody();
            return ((LibrarySystem.App.TestService.TestSoapServiceSoap)(this)).TestInternalServerErrorExceptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibrarySystem.App.TestService.TestMethodNotAllowedExceptionResponse LibrarySystem.App.TestService.TestSoapServiceSoap.TestMethodNotAllowedException(LibrarySystem.App.TestService.TestMethodNotAllowedExceptionRequest request) {
            return base.Channel.TestMethodNotAllowedException(request);
        }
        
        public string TestMethodNotAllowedException() {
            LibrarySystem.App.TestService.TestMethodNotAllowedExceptionRequest inValue = new LibrarySystem.App.TestService.TestMethodNotAllowedExceptionRequest();
            inValue.Body = new LibrarySystem.App.TestService.TestMethodNotAllowedExceptionRequestBody();
            LibrarySystem.App.TestService.TestMethodNotAllowedExceptionResponse retVal = ((LibrarySystem.App.TestService.TestSoapServiceSoap)(this)).TestMethodNotAllowedException(inValue);
            return retVal.Body.TestMethodNotAllowedExceptionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestMethodNotAllowedExceptionResponse> LibrarySystem.App.TestService.TestSoapServiceSoap.TestMethodNotAllowedExceptionAsync(LibrarySystem.App.TestService.TestMethodNotAllowedExceptionRequest request) {
            return base.Channel.TestMethodNotAllowedExceptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestMethodNotAllowedExceptionResponse> TestMethodNotAllowedExceptionAsync() {
            LibrarySystem.App.TestService.TestMethodNotAllowedExceptionRequest inValue = new LibrarySystem.App.TestService.TestMethodNotAllowedExceptionRequest();
            inValue.Body = new LibrarySystem.App.TestService.TestMethodNotAllowedExceptionRequestBody();
            return ((LibrarySystem.App.TestService.TestSoapServiceSoap)(this)).TestMethodNotAllowedExceptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibrarySystem.App.TestService.TestNotFoundExceptionResponse LibrarySystem.App.TestService.TestSoapServiceSoap.TestNotFoundException(LibrarySystem.App.TestService.TestNotFoundExceptionRequest request) {
            return base.Channel.TestNotFoundException(request);
        }
        
        public string TestNotFoundException() {
            LibrarySystem.App.TestService.TestNotFoundExceptionRequest inValue = new LibrarySystem.App.TestService.TestNotFoundExceptionRequest();
            inValue.Body = new LibrarySystem.App.TestService.TestNotFoundExceptionRequestBody();
            LibrarySystem.App.TestService.TestNotFoundExceptionResponse retVal = ((LibrarySystem.App.TestService.TestSoapServiceSoap)(this)).TestNotFoundException(inValue);
            return retVal.Body.TestNotFoundExceptionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestNotFoundExceptionResponse> LibrarySystem.App.TestService.TestSoapServiceSoap.TestNotFoundExceptionAsync(LibrarySystem.App.TestService.TestNotFoundExceptionRequest request) {
            return base.Channel.TestNotFoundExceptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestNotFoundExceptionResponse> TestNotFoundExceptionAsync() {
            LibrarySystem.App.TestService.TestNotFoundExceptionRequest inValue = new LibrarySystem.App.TestService.TestNotFoundExceptionRequest();
            inValue.Body = new LibrarySystem.App.TestService.TestNotFoundExceptionRequestBody();
            return ((LibrarySystem.App.TestService.TestSoapServiceSoap)(this)).TestNotFoundExceptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibrarySystem.App.TestService.TestResourceAlreadyExistsExceptionResponse LibrarySystem.App.TestService.TestSoapServiceSoap.TestResourceAlreadyExistsException(LibrarySystem.App.TestService.TestResourceAlreadyExistsExceptionRequest request) {
            return base.Channel.TestResourceAlreadyExistsException(request);
        }
        
        public string TestResourceAlreadyExistsException() {
            LibrarySystem.App.TestService.TestResourceAlreadyExistsExceptionRequest inValue = new LibrarySystem.App.TestService.TestResourceAlreadyExistsExceptionRequest();
            inValue.Body = new LibrarySystem.App.TestService.TestResourceAlreadyExistsExceptionRequestBody();
            LibrarySystem.App.TestService.TestResourceAlreadyExistsExceptionResponse retVal = ((LibrarySystem.App.TestService.TestSoapServiceSoap)(this)).TestResourceAlreadyExistsException(inValue);
            return retVal.Body.TestResourceAlreadyExistsExceptionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestResourceAlreadyExistsExceptionResponse> LibrarySystem.App.TestService.TestSoapServiceSoap.TestResourceAlreadyExistsExceptionAsync(LibrarySystem.App.TestService.TestResourceAlreadyExistsExceptionRequest request) {
            return base.Channel.TestResourceAlreadyExistsExceptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestResourceAlreadyExistsExceptionResponse> TestResourceAlreadyExistsExceptionAsync() {
            LibrarySystem.App.TestService.TestResourceAlreadyExistsExceptionRequest inValue = new LibrarySystem.App.TestService.TestResourceAlreadyExistsExceptionRequest();
            inValue.Body = new LibrarySystem.App.TestService.TestResourceAlreadyExistsExceptionRequestBody();
            return ((LibrarySystem.App.TestService.TestSoapServiceSoap)(this)).TestResourceAlreadyExistsExceptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibrarySystem.App.TestService.TestUnauthorizedExceptionResponse LibrarySystem.App.TestService.TestSoapServiceSoap.TestUnauthorizedException(LibrarySystem.App.TestService.TestUnauthorizedExceptionRequest request) {
            return base.Channel.TestUnauthorizedException(request);
        }
        
        public string TestUnauthorizedException() {
            LibrarySystem.App.TestService.TestUnauthorizedExceptionRequest inValue = new LibrarySystem.App.TestService.TestUnauthorizedExceptionRequest();
            inValue.Body = new LibrarySystem.App.TestService.TestUnauthorizedExceptionRequestBody();
            LibrarySystem.App.TestService.TestUnauthorizedExceptionResponse retVal = ((LibrarySystem.App.TestService.TestSoapServiceSoap)(this)).TestUnauthorizedException(inValue);
            return retVal.Body.TestUnauthorizedExceptionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestUnauthorizedExceptionResponse> LibrarySystem.App.TestService.TestSoapServiceSoap.TestUnauthorizedExceptionAsync(LibrarySystem.App.TestService.TestUnauthorizedExceptionRequest request) {
            return base.Channel.TestUnauthorizedExceptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestUnauthorizedExceptionResponse> TestUnauthorizedExceptionAsync() {
            LibrarySystem.App.TestService.TestUnauthorizedExceptionRequest inValue = new LibrarySystem.App.TestService.TestUnauthorizedExceptionRequest();
            inValue.Body = new LibrarySystem.App.TestService.TestUnauthorizedExceptionRequestBody();
            return ((LibrarySystem.App.TestService.TestSoapServiceSoap)(this)).TestUnauthorizedExceptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibrarySystem.App.TestService.TestUnprocessableEntityExceptionResponse LibrarySystem.App.TestService.TestSoapServiceSoap.TestUnprocessableEntityException(LibrarySystem.App.TestService.TestUnprocessableEntityExceptionRequest request) {
            return base.Channel.TestUnprocessableEntityException(request);
        }
        
        public string TestUnprocessableEntityException() {
            LibrarySystem.App.TestService.TestUnprocessableEntityExceptionRequest inValue = new LibrarySystem.App.TestService.TestUnprocessableEntityExceptionRequest();
            inValue.Body = new LibrarySystem.App.TestService.TestUnprocessableEntityExceptionRequestBody();
            LibrarySystem.App.TestService.TestUnprocessableEntityExceptionResponse retVal = ((LibrarySystem.App.TestService.TestSoapServiceSoap)(this)).TestUnprocessableEntityException(inValue);
            return retVal.Body.TestUnprocessableEntityExceptionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestUnprocessableEntityExceptionResponse> LibrarySystem.App.TestService.TestSoapServiceSoap.TestUnprocessableEntityExceptionAsync(LibrarySystem.App.TestService.TestUnprocessableEntityExceptionRequest request) {
            return base.Channel.TestUnprocessableEntityExceptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestUnprocessableEntityExceptionResponse> TestUnprocessableEntityExceptionAsync() {
            LibrarySystem.App.TestService.TestUnprocessableEntityExceptionRequest inValue = new LibrarySystem.App.TestService.TestUnprocessableEntityExceptionRequest();
            inValue.Body = new LibrarySystem.App.TestService.TestUnprocessableEntityExceptionRequestBody();
            return ((LibrarySystem.App.TestService.TestSoapServiceSoap)(this)).TestUnprocessableEntityExceptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibrarySystem.App.TestService.TestValidationExceptionResponse LibrarySystem.App.TestService.TestSoapServiceSoap.TestValidationException(LibrarySystem.App.TestService.TestValidationExceptionRequest request) {
            return base.Channel.TestValidationException(request);
        }
        
        public string TestValidationException() {
            LibrarySystem.App.TestService.TestValidationExceptionRequest inValue = new LibrarySystem.App.TestService.TestValidationExceptionRequest();
            inValue.Body = new LibrarySystem.App.TestService.TestValidationExceptionRequestBody();
            LibrarySystem.App.TestService.TestValidationExceptionResponse retVal = ((LibrarySystem.App.TestService.TestSoapServiceSoap)(this)).TestValidationException(inValue);
            return retVal.Body.TestValidationExceptionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestValidationExceptionResponse> LibrarySystem.App.TestService.TestSoapServiceSoap.TestValidationExceptionAsync(LibrarySystem.App.TestService.TestValidationExceptionRequest request) {
            return base.Channel.TestValidationExceptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.TestService.TestValidationExceptionResponse> TestValidationExceptionAsync() {
            LibrarySystem.App.TestService.TestValidationExceptionRequest inValue = new LibrarySystem.App.TestService.TestValidationExceptionRequest();
            inValue.Body = new LibrarySystem.App.TestService.TestValidationExceptionRequestBody();
            return ((LibrarySystem.App.TestService.TestSoapServiceSoap)(this)).TestValidationExceptionAsync(inValue);
        }
    }
}
