//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem.App.BookService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfListOfBookViewDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResponseOfListOfBookViewDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LibrarySystem.App.BookService.BookViewDto[] DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public LibrarySystem.App.BookService.BookViewDto[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookViewDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BookViewDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookNameField;
        
        private int PublishYearField;
        
        private int PagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublisherField;
        
        private int AuthorField;
        
        private int CategoryField;
        
        private int LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ISBN {
            get {
                return this.ISBNField;
            }
            set {
                if ((object.ReferenceEquals(this.ISBNField, value) != true)) {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BookName {
            get {
                return this.BookNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BookNameField, value) != true)) {
                    this.BookNameField = value;
                    this.RaisePropertyChanged("BookName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int PublishYear {
            get {
                return this.PublishYearField;
            }
            set {
                if ((this.PublishYearField.Equals(value) != true)) {
                    this.PublishYearField = value;
                    this.RaisePropertyChanged("PublishYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Pages {
            get {
                return this.PagesField;
            }
            set {
                if ((this.PagesField.Equals(value) != true)) {
                    this.PagesField = value;
                    this.RaisePropertyChanged("Pages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Publisher {
            get {
                return this.PublisherField;
            }
            set {
                if ((object.ReferenceEquals(this.PublisherField, value) != true)) {
                    this.PublisherField = value;
                    this.RaisePropertyChanged("Publisher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((this.AuthorField.Equals(value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((this.CategoryField.Equals(value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((this.LanguageField.Equals(value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string AuthorName {
            get {
                return this.AuthorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorNameField, value) != true)) {
                    this.AuthorNameField = value;
                    this.RaisePropertyChanged("AuthorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string LanguageName {
            get {
                return this.LanguageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageNameField, value) != true)) {
                    this.LanguageNameField = value;
                    this.RaisePropertyChanged("LanguageName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfBookViewDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResponseOfBookViewDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LibrarySystem.App.BookService.BookViewDto DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public LibrarySystem.App.BookService.BookViewDto Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BookDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookNameField;
        
        private int AuthorField;
        
        private int CategoryField;
        
        private int LanguageField;
        
        private int PublishYearField;
        
        private int PagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublisherField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ISBN {
            get {
                return this.ISBNField;
            }
            set {
                if ((object.ReferenceEquals(this.ISBNField, value) != true)) {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BookName {
            get {
                return this.BookNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BookNameField, value) != true)) {
                    this.BookNameField = value;
                    this.RaisePropertyChanged("BookName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((this.AuthorField.Equals(value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((this.CategoryField.Equals(value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((this.LanguageField.Equals(value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int PublishYear {
            get {
                return this.PublishYearField;
            }
            set {
                if ((this.PublishYearField.Equals(value) != true)) {
                    this.PublishYearField = value;
                    this.RaisePropertyChanged("PublishYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Pages {
            get {
                return this.PagesField;
            }
            set {
                if ((this.PagesField.Equals(value) != true)) {
                    this.PagesField = value;
                    this.RaisePropertyChanged("Pages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Publisher {
            get {
                return this.PublisherField;
            }
            set {
                if ((object.ReferenceEquals(this.PublisherField, value) != true)) {
                    this.PublisherField = value;
                    this.RaisePropertyChanged("Publisher");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfBoolean", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResponseOfBoolean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        private bool DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookSearchCriteriaDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BookSearchCriteriaDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorNameField;
        
        private System.Nullable<int> CategoryIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BookName {
            get {
                return this.BookNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BookNameField, value) != true)) {
                    this.BookNameField = value;
                    this.RaisePropertyChanged("BookName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AuthorName {
            get {
                return this.AuthorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorNameField, value) != true)) {
                    this.AuthorNameField = value;
                    this.RaisePropertyChanged("AuthorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<int> CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookService.BookSoapServiceSoap")]
    public interface BookSoapServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        LibrarySystem.App.BookService.GetAllResponse GetAll(LibrarySystem.App.BookService.GetAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.BookService.GetAllResponse> GetAllAsync(LibrarySystem.App.BookService.GetAllRequest request);
        
        // CODEGEN: Generating message contract since element name isbn from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByISBN", ReplyAction="*")]
        LibrarySystem.App.BookService.GetByISBNResponse GetByISBN(LibrarySystem.App.BookService.GetByISBNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByISBN", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.BookService.GetByISBNResponse> GetByISBNAsync(LibrarySystem.App.BookService.GetByISBNRequest request);
        
        // CODEGEN: Generating message contract since element name dto from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        LibrarySystem.App.BookService.AddResponse Add(LibrarySystem.App.BookService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.BookService.AddResponse> AddAsync(LibrarySystem.App.BookService.AddRequest request);
        
        // CODEGEN: Generating message contract since element name dto from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        LibrarySystem.App.BookService.UpdateResponse Update(LibrarySystem.App.BookService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.BookService.UpdateResponse> UpdateAsync(LibrarySystem.App.BookService.UpdateRequest request);
        
        // CODEGEN: Generating message contract since element name isbn from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        LibrarySystem.App.BookService.DeleteResponse Delete(LibrarySystem.App.BookService.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.BookService.DeleteResponse> DeleteAsync(LibrarySystem.App.BookService.DeleteRequest request);
        
        // CODEGEN: Generating message contract since element name dto from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search", ReplyAction="*")]
        LibrarySystem.App.BookService.SearchResponse Search(LibrarySystem.App.BookService.SearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.BookService.SearchResponse> SearchAsync(LibrarySystem.App.BookService.SearchRequest request);
        
        // CODEGEN: Generating message contract since element name GetAvailableBooksResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAvailableBooks", ReplyAction="*")]
        LibrarySystem.App.BookService.GetAvailableBooksResponse GetAvailableBooks(LibrarySystem.App.BookService.GetAvailableBooksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAvailableBooks", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.BookService.GetAvailableBooksResponse> GetAvailableBooksAsync(LibrarySystem.App.BookService.GetAvailableBooksRequest request);
        
        // CODEGEN: Generating message contract since element name isbn from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAvailableBookByISBN", ReplyAction="*")]
        LibrarySystem.App.BookService.GetAvailableBookByISBNResponse GetAvailableBookByISBN(LibrarySystem.App.BookService.GetAvailableBookByISBNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAvailableBookByISBN", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.BookService.GetAvailableBookByISBNResponse> GetAvailableBookByISBNAsync(LibrarySystem.App.BookService.GetAvailableBookByISBNRequest request);
        
        // CODEGEN: Generating message contract since element name isbn from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBorrowedBookByUserIdAndISBN", ReplyAction="*")]
        LibrarySystem.App.BookService.GetBorrowedBookByUserIdAndISBNResponse GetBorrowedBookByUserIdAndISBN(LibrarySystem.App.BookService.GetBorrowedBookByUserIdAndISBNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBorrowedBookByUserIdAndISBN", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.BookService.GetBorrowedBookByUserIdAndISBNResponse> GetBorrowedBookByUserIdAndISBNAsync(LibrarySystem.App.BookService.GetBorrowedBookByUserIdAndISBNRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAll", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.BookService.GetAllRequestBody Body;
        
        public GetAllRequest() {
        }
        
        public GetAllRequest(LibrarySystem.App.BookService.GetAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllRequestBody {
        
        public GetAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.BookService.GetAllResponseBody Body;
        
        public GetAllResponse() {
        }
        
        public GetAllResponse(LibrarySystem.App.BookService.GetAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LibrarySystem.App.BookService.ResponseOfListOfBookViewDto GetAllResult;
        
        public GetAllResponseBody() {
        }
        
        public GetAllResponseBody(LibrarySystem.App.BookService.ResponseOfListOfBookViewDto GetAllResult) {
            this.GetAllResult = GetAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByISBNRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByISBN", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.BookService.GetByISBNRequestBody Body;
        
        public GetByISBNRequest() {
        }
        
        public GetByISBNRequest(LibrarySystem.App.BookService.GetByISBNRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByISBNRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string isbn;
        
        public GetByISBNRequestBody() {
        }
        
        public GetByISBNRequestBody(string isbn) {
            this.isbn = isbn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByISBNResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByISBNResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.BookService.GetByISBNResponseBody Body;
        
        public GetByISBNResponse() {
        }
        
        public GetByISBNResponse(LibrarySystem.App.BookService.GetByISBNResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByISBNResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LibrarySystem.App.BookService.ResponseOfBookViewDto GetByISBNResult;
        
        public GetByISBNResponseBody() {
        }
        
        public GetByISBNResponseBody(LibrarySystem.App.BookService.ResponseOfBookViewDto GetByISBNResult) {
            this.GetByISBNResult = GetByISBNResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.BookService.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(LibrarySystem.App.BookService.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LibrarySystem.App.BookService.BookDto dto;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(LibrarySystem.App.BookService.BookDto dto) {
            this.dto = dto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.BookService.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(LibrarySystem.App.BookService.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LibrarySystem.App.BookService.ResponseOfBookViewDto AddResult;
        
        public AddResponseBody() {
        }
        
        public AddResponseBody(LibrarySystem.App.BookService.ResponseOfBookViewDto AddResult) {
            this.AddResult = AddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.BookService.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(LibrarySystem.App.BookService.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LibrarySystem.App.BookService.BookDto dto;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(LibrarySystem.App.BookService.BookDto dto) {
            this.dto = dto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.BookService.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(LibrarySystem.App.BookService.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LibrarySystem.App.BookService.ResponseOfBookViewDto UpdateResult;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(LibrarySystem.App.BookService.ResponseOfBookViewDto UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.BookService.DeleteRequestBody Body;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(LibrarySystem.App.BookService.DeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string isbn;
        
        public DeleteRequestBody() {
        }
        
        public DeleteRequestBody(string isbn) {
            this.isbn = isbn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.BookService.DeleteResponseBody Body;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(LibrarySystem.App.BookService.DeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LibrarySystem.App.BookService.ResponseOfBoolean DeleteResult;
        
        public DeleteResponseBody() {
        }
        
        public DeleteResponseBody(LibrarySystem.App.BookService.ResponseOfBoolean DeleteResult) {
            this.DeleteResult = DeleteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Search", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.BookService.SearchRequestBody Body;
        
        public SearchRequest() {
        }
        
        public SearchRequest(LibrarySystem.App.BookService.SearchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LibrarySystem.App.BookService.BookSearchCriteriaDto dto;
        
        public SearchRequestBody() {
        }
        
        public SearchRequestBody(LibrarySystem.App.BookService.BookSearchCriteriaDto dto) {
            this.dto = dto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.BookService.SearchResponseBody Body;
        
        public SearchResponse() {
        }
        
        public SearchResponse(LibrarySystem.App.BookService.SearchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LibrarySystem.App.BookService.ResponseOfListOfBookViewDto SearchResult;
        
        public SearchResponseBody() {
        }
        
        public SearchResponseBody(LibrarySystem.App.BookService.ResponseOfListOfBookViewDto SearchResult) {
            this.SearchResult = SearchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAvailableBooksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAvailableBooks", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.BookService.GetAvailableBooksRequestBody Body;
        
        public GetAvailableBooksRequest() {
        }
        
        public GetAvailableBooksRequest(LibrarySystem.App.BookService.GetAvailableBooksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAvailableBooksRequestBody {
        
        public GetAvailableBooksRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAvailableBooksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAvailableBooksResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.BookService.GetAvailableBooksResponseBody Body;
        
        public GetAvailableBooksResponse() {
        }
        
        public GetAvailableBooksResponse(LibrarySystem.App.BookService.GetAvailableBooksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAvailableBooksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LibrarySystem.App.BookService.ResponseOfListOfBookViewDto GetAvailableBooksResult;
        
        public GetAvailableBooksResponseBody() {
        }
        
        public GetAvailableBooksResponseBody(LibrarySystem.App.BookService.ResponseOfListOfBookViewDto GetAvailableBooksResult) {
            this.GetAvailableBooksResult = GetAvailableBooksResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAvailableBookByISBNRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAvailableBookByISBN", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.BookService.GetAvailableBookByISBNRequestBody Body;
        
        public GetAvailableBookByISBNRequest() {
        }
        
        public GetAvailableBookByISBNRequest(LibrarySystem.App.BookService.GetAvailableBookByISBNRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAvailableBookByISBNRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string isbn;
        
        public GetAvailableBookByISBNRequestBody() {
        }
        
        public GetAvailableBookByISBNRequestBody(string isbn) {
            this.isbn = isbn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAvailableBookByISBNResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAvailableBookByISBNResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.BookService.GetAvailableBookByISBNResponseBody Body;
        
        public GetAvailableBookByISBNResponse() {
        }
        
        public GetAvailableBookByISBNResponse(LibrarySystem.App.BookService.GetAvailableBookByISBNResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAvailableBookByISBNResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LibrarySystem.App.BookService.ResponseOfBookViewDto GetAvailableBookByISBNResult;
        
        public GetAvailableBookByISBNResponseBody() {
        }
        
        public GetAvailableBookByISBNResponseBody(LibrarySystem.App.BookService.ResponseOfBookViewDto GetAvailableBookByISBNResult) {
            this.GetAvailableBookByISBNResult = GetAvailableBookByISBNResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBorrowedBookByUserIdAndISBNRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBorrowedBookByUserIdAndISBN", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.BookService.GetBorrowedBookByUserIdAndISBNRequestBody Body;
        
        public GetBorrowedBookByUserIdAndISBNRequest() {
        }
        
        public GetBorrowedBookByUserIdAndISBNRequest(LibrarySystem.App.BookService.GetBorrowedBookByUserIdAndISBNRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBorrowedBookByUserIdAndISBNRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string isbn;
        
        public GetBorrowedBookByUserIdAndISBNRequestBody() {
        }
        
        public GetBorrowedBookByUserIdAndISBNRequestBody(int userId, string isbn) {
            this.userId = userId;
            this.isbn = isbn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBorrowedBookByUserIdAndISBNResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBorrowedBookByUserIdAndISBNResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibrarySystem.App.BookService.GetBorrowedBookByUserIdAndISBNResponseBody Body;
        
        public GetBorrowedBookByUserIdAndISBNResponse() {
        }
        
        public GetBorrowedBookByUserIdAndISBNResponse(LibrarySystem.App.BookService.GetBorrowedBookByUserIdAndISBNResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBorrowedBookByUserIdAndISBNResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LibrarySystem.App.BookService.ResponseOfBookViewDto GetBorrowedBookByUserIdAndISBNResult;
        
        public GetBorrowedBookByUserIdAndISBNResponseBody() {
        }
        
        public GetBorrowedBookByUserIdAndISBNResponseBody(LibrarySystem.App.BookService.ResponseOfBookViewDto GetBorrowedBookByUserIdAndISBNResult) {
            this.GetBorrowedBookByUserIdAndISBNResult = GetBorrowedBookByUserIdAndISBNResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BookSoapServiceSoapChannel : LibrarySystem.App.BookService.BookSoapServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookSoapServiceSoapClient : System.ServiceModel.ClientBase<LibrarySystem.App.BookService.BookSoapServiceSoap>, LibrarySystem.App.BookService.BookSoapServiceSoap {
        
        public BookSoapServiceSoapClient() {
        }
        
        public BookSoapServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookSoapServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookSoapServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookSoapServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibrarySystem.App.BookService.GetAllResponse LibrarySystem.App.BookService.BookSoapServiceSoap.GetAll(LibrarySystem.App.BookService.GetAllRequest request) {
            return base.Channel.GetAll(request);
        }
        
        public LibrarySystem.App.BookService.ResponseOfListOfBookViewDto GetAll() {
            LibrarySystem.App.BookService.GetAllRequest inValue = new LibrarySystem.App.BookService.GetAllRequest();
            inValue.Body = new LibrarySystem.App.BookService.GetAllRequestBody();
            LibrarySystem.App.BookService.GetAllResponse retVal = ((LibrarySystem.App.BookService.BookSoapServiceSoap)(this)).GetAll(inValue);
            return retVal.Body.GetAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySystem.App.BookService.GetAllResponse> LibrarySystem.App.BookService.BookSoapServiceSoap.GetAllAsync(LibrarySystem.App.BookService.GetAllRequest request) {
            return base.Channel.GetAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.BookService.GetAllResponse> GetAllAsync() {
            LibrarySystem.App.BookService.GetAllRequest inValue = new LibrarySystem.App.BookService.GetAllRequest();
            inValue.Body = new LibrarySystem.App.BookService.GetAllRequestBody();
            return ((LibrarySystem.App.BookService.BookSoapServiceSoap)(this)).GetAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibrarySystem.App.BookService.GetByISBNResponse LibrarySystem.App.BookService.BookSoapServiceSoap.GetByISBN(LibrarySystem.App.BookService.GetByISBNRequest request) {
            return base.Channel.GetByISBN(request);
        }
        
        public LibrarySystem.App.BookService.ResponseOfBookViewDto GetByISBN(string isbn) {
            LibrarySystem.App.BookService.GetByISBNRequest inValue = new LibrarySystem.App.BookService.GetByISBNRequest();
            inValue.Body = new LibrarySystem.App.BookService.GetByISBNRequestBody();
            inValue.Body.isbn = isbn;
            LibrarySystem.App.BookService.GetByISBNResponse retVal = ((LibrarySystem.App.BookService.BookSoapServiceSoap)(this)).GetByISBN(inValue);
            return retVal.Body.GetByISBNResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySystem.App.BookService.GetByISBNResponse> LibrarySystem.App.BookService.BookSoapServiceSoap.GetByISBNAsync(LibrarySystem.App.BookService.GetByISBNRequest request) {
            return base.Channel.GetByISBNAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.BookService.GetByISBNResponse> GetByISBNAsync(string isbn) {
            LibrarySystem.App.BookService.GetByISBNRequest inValue = new LibrarySystem.App.BookService.GetByISBNRequest();
            inValue.Body = new LibrarySystem.App.BookService.GetByISBNRequestBody();
            inValue.Body.isbn = isbn;
            return ((LibrarySystem.App.BookService.BookSoapServiceSoap)(this)).GetByISBNAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibrarySystem.App.BookService.AddResponse LibrarySystem.App.BookService.BookSoapServiceSoap.Add(LibrarySystem.App.BookService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public LibrarySystem.App.BookService.ResponseOfBookViewDto Add(LibrarySystem.App.BookService.BookDto dto) {
            LibrarySystem.App.BookService.AddRequest inValue = new LibrarySystem.App.BookService.AddRequest();
            inValue.Body = new LibrarySystem.App.BookService.AddRequestBody();
            inValue.Body.dto = dto;
            LibrarySystem.App.BookService.AddResponse retVal = ((LibrarySystem.App.BookService.BookSoapServiceSoap)(this)).Add(inValue);
            return retVal.Body.AddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySystem.App.BookService.AddResponse> LibrarySystem.App.BookService.BookSoapServiceSoap.AddAsync(LibrarySystem.App.BookService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.BookService.AddResponse> AddAsync(LibrarySystem.App.BookService.BookDto dto) {
            LibrarySystem.App.BookService.AddRequest inValue = new LibrarySystem.App.BookService.AddRequest();
            inValue.Body = new LibrarySystem.App.BookService.AddRequestBody();
            inValue.Body.dto = dto;
            return ((LibrarySystem.App.BookService.BookSoapServiceSoap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibrarySystem.App.BookService.UpdateResponse LibrarySystem.App.BookService.BookSoapServiceSoap.Update(LibrarySystem.App.BookService.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public LibrarySystem.App.BookService.ResponseOfBookViewDto Update(LibrarySystem.App.BookService.BookDto dto) {
            LibrarySystem.App.BookService.UpdateRequest inValue = new LibrarySystem.App.BookService.UpdateRequest();
            inValue.Body = new LibrarySystem.App.BookService.UpdateRequestBody();
            inValue.Body.dto = dto;
            LibrarySystem.App.BookService.UpdateResponse retVal = ((LibrarySystem.App.BookService.BookSoapServiceSoap)(this)).Update(inValue);
            return retVal.Body.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySystem.App.BookService.UpdateResponse> LibrarySystem.App.BookService.BookSoapServiceSoap.UpdateAsync(LibrarySystem.App.BookService.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.BookService.UpdateResponse> UpdateAsync(LibrarySystem.App.BookService.BookDto dto) {
            LibrarySystem.App.BookService.UpdateRequest inValue = new LibrarySystem.App.BookService.UpdateRequest();
            inValue.Body = new LibrarySystem.App.BookService.UpdateRequestBody();
            inValue.Body.dto = dto;
            return ((LibrarySystem.App.BookService.BookSoapServiceSoap)(this)).UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibrarySystem.App.BookService.DeleteResponse LibrarySystem.App.BookService.BookSoapServiceSoap.Delete(LibrarySystem.App.BookService.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public LibrarySystem.App.BookService.ResponseOfBoolean Delete(string isbn) {
            LibrarySystem.App.BookService.DeleteRequest inValue = new LibrarySystem.App.BookService.DeleteRequest();
            inValue.Body = new LibrarySystem.App.BookService.DeleteRequestBody();
            inValue.Body.isbn = isbn;
            LibrarySystem.App.BookService.DeleteResponse retVal = ((LibrarySystem.App.BookService.BookSoapServiceSoap)(this)).Delete(inValue);
            return retVal.Body.DeleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySystem.App.BookService.DeleteResponse> LibrarySystem.App.BookService.BookSoapServiceSoap.DeleteAsync(LibrarySystem.App.BookService.DeleteRequest request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.BookService.DeleteResponse> DeleteAsync(string isbn) {
            LibrarySystem.App.BookService.DeleteRequest inValue = new LibrarySystem.App.BookService.DeleteRequest();
            inValue.Body = new LibrarySystem.App.BookService.DeleteRequestBody();
            inValue.Body.isbn = isbn;
            return ((LibrarySystem.App.BookService.BookSoapServiceSoap)(this)).DeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibrarySystem.App.BookService.SearchResponse LibrarySystem.App.BookService.BookSoapServiceSoap.Search(LibrarySystem.App.BookService.SearchRequest request) {
            return base.Channel.Search(request);
        }
        
        public LibrarySystem.App.BookService.ResponseOfListOfBookViewDto Search(LibrarySystem.App.BookService.BookSearchCriteriaDto dto) {
            LibrarySystem.App.BookService.SearchRequest inValue = new LibrarySystem.App.BookService.SearchRequest();
            inValue.Body = new LibrarySystem.App.BookService.SearchRequestBody();
            inValue.Body.dto = dto;
            LibrarySystem.App.BookService.SearchResponse retVal = ((LibrarySystem.App.BookService.BookSoapServiceSoap)(this)).Search(inValue);
            return retVal.Body.SearchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySystem.App.BookService.SearchResponse> LibrarySystem.App.BookService.BookSoapServiceSoap.SearchAsync(LibrarySystem.App.BookService.SearchRequest request) {
            return base.Channel.SearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.BookService.SearchResponse> SearchAsync(LibrarySystem.App.BookService.BookSearchCriteriaDto dto) {
            LibrarySystem.App.BookService.SearchRequest inValue = new LibrarySystem.App.BookService.SearchRequest();
            inValue.Body = new LibrarySystem.App.BookService.SearchRequestBody();
            inValue.Body.dto = dto;
            return ((LibrarySystem.App.BookService.BookSoapServiceSoap)(this)).SearchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibrarySystem.App.BookService.GetAvailableBooksResponse LibrarySystem.App.BookService.BookSoapServiceSoap.GetAvailableBooks(LibrarySystem.App.BookService.GetAvailableBooksRequest request) {
            return base.Channel.GetAvailableBooks(request);
        }
        
        public LibrarySystem.App.BookService.ResponseOfListOfBookViewDto GetAvailableBooks() {
            LibrarySystem.App.BookService.GetAvailableBooksRequest inValue = new LibrarySystem.App.BookService.GetAvailableBooksRequest();
            inValue.Body = new LibrarySystem.App.BookService.GetAvailableBooksRequestBody();
            LibrarySystem.App.BookService.GetAvailableBooksResponse retVal = ((LibrarySystem.App.BookService.BookSoapServiceSoap)(this)).GetAvailableBooks(inValue);
            return retVal.Body.GetAvailableBooksResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySystem.App.BookService.GetAvailableBooksResponse> LibrarySystem.App.BookService.BookSoapServiceSoap.GetAvailableBooksAsync(LibrarySystem.App.BookService.GetAvailableBooksRequest request) {
            return base.Channel.GetAvailableBooksAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.BookService.GetAvailableBooksResponse> GetAvailableBooksAsync() {
            LibrarySystem.App.BookService.GetAvailableBooksRequest inValue = new LibrarySystem.App.BookService.GetAvailableBooksRequest();
            inValue.Body = new LibrarySystem.App.BookService.GetAvailableBooksRequestBody();
            return ((LibrarySystem.App.BookService.BookSoapServiceSoap)(this)).GetAvailableBooksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibrarySystem.App.BookService.GetAvailableBookByISBNResponse LibrarySystem.App.BookService.BookSoapServiceSoap.GetAvailableBookByISBN(LibrarySystem.App.BookService.GetAvailableBookByISBNRequest request) {
            return base.Channel.GetAvailableBookByISBN(request);
        }
        
        public LibrarySystem.App.BookService.ResponseOfBookViewDto GetAvailableBookByISBN(string isbn) {
            LibrarySystem.App.BookService.GetAvailableBookByISBNRequest inValue = new LibrarySystem.App.BookService.GetAvailableBookByISBNRequest();
            inValue.Body = new LibrarySystem.App.BookService.GetAvailableBookByISBNRequestBody();
            inValue.Body.isbn = isbn;
            LibrarySystem.App.BookService.GetAvailableBookByISBNResponse retVal = ((LibrarySystem.App.BookService.BookSoapServiceSoap)(this)).GetAvailableBookByISBN(inValue);
            return retVal.Body.GetAvailableBookByISBNResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySystem.App.BookService.GetAvailableBookByISBNResponse> LibrarySystem.App.BookService.BookSoapServiceSoap.GetAvailableBookByISBNAsync(LibrarySystem.App.BookService.GetAvailableBookByISBNRequest request) {
            return base.Channel.GetAvailableBookByISBNAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.BookService.GetAvailableBookByISBNResponse> GetAvailableBookByISBNAsync(string isbn) {
            LibrarySystem.App.BookService.GetAvailableBookByISBNRequest inValue = new LibrarySystem.App.BookService.GetAvailableBookByISBNRequest();
            inValue.Body = new LibrarySystem.App.BookService.GetAvailableBookByISBNRequestBody();
            inValue.Body.isbn = isbn;
            return ((LibrarySystem.App.BookService.BookSoapServiceSoap)(this)).GetAvailableBookByISBNAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibrarySystem.App.BookService.GetBorrowedBookByUserIdAndISBNResponse LibrarySystem.App.BookService.BookSoapServiceSoap.GetBorrowedBookByUserIdAndISBN(LibrarySystem.App.BookService.GetBorrowedBookByUserIdAndISBNRequest request) {
            return base.Channel.GetBorrowedBookByUserIdAndISBN(request);
        }
        
        public LibrarySystem.App.BookService.ResponseOfBookViewDto GetBorrowedBookByUserIdAndISBN(int userId, string isbn) {
            LibrarySystem.App.BookService.GetBorrowedBookByUserIdAndISBNRequest inValue = new LibrarySystem.App.BookService.GetBorrowedBookByUserIdAndISBNRequest();
            inValue.Body = new LibrarySystem.App.BookService.GetBorrowedBookByUserIdAndISBNRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.isbn = isbn;
            LibrarySystem.App.BookService.GetBorrowedBookByUserIdAndISBNResponse retVal = ((LibrarySystem.App.BookService.BookSoapServiceSoap)(this)).GetBorrowedBookByUserIdAndISBN(inValue);
            return retVal.Body.GetBorrowedBookByUserIdAndISBNResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibrarySystem.App.BookService.GetBorrowedBookByUserIdAndISBNResponse> LibrarySystem.App.BookService.BookSoapServiceSoap.GetBorrowedBookByUserIdAndISBNAsync(LibrarySystem.App.BookService.GetBorrowedBookByUserIdAndISBNRequest request) {
            return base.Channel.GetBorrowedBookByUserIdAndISBNAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.BookService.GetBorrowedBookByUserIdAndISBNResponse> GetBorrowedBookByUserIdAndISBNAsync(int userId, string isbn) {
            LibrarySystem.App.BookService.GetBorrowedBookByUserIdAndISBNRequest inValue = new LibrarySystem.App.BookService.GetBorrowedBookByUserIdAndISBNRequest();
            inValue.Body = new LibrarySystem.App.BookService.GetBorrowedBookByUserIdAndISBNRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.isbn = isbn;
            return ((LibrarySystem.App.BookService.BookSoapServiceSoap)(this)).GetBorrowedBookByUserIdAndISBNAsync(inValue);
        }
    }
}
