//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem.App.BookLoanService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookLoanService.BookLoanSoapServiceSoap")]
    public interface BookLoanSoapServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Borrow", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LibrarySystem.App.BookLoanService.ResponseOfBorrowViewDto Borrow(LibrarySystem.App.BookLoanService.BorrowCreateDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Borrow", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.BookLoanService.ResponseOfBorrowViewDto> BorrowAsync(LibrarySystem.App.BookLoanService.BorrowCreateDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Return", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LibrarySystem.App.BookLoanService.ResponseOfBorrowViewDto Return(LibrarySystem.App.BookLoanService.BorrowReturnDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Return", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.BookLoanService.ResponseOfBorrowViewDto> ReturnAsync(LibrarySystem.App.BookLoanService.BorrowReturnDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LibrarySystem.App.BookLoanService.ResponseOfBorrowViewDto GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetById", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.BookLoanService.ResponseOfBorrowViewDto> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUnreturnedLoansByUserId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LibrarySystem.App.BookLoanService.ResponseOfDataTable GetUnreturnedLoansByUserId(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUnreturnedLoansByUserId", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.BookLoanService.ResponseOfDataTable> GetUnreturnedLoansByUserIdAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LibrarySystem.App.BookLoanService.ResponseOfDataTable GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.BookLoanService.ResponseOfDataTable> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllByUserId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LibrarySystem.App.BookLoanService.ResponseOfDataTable GetAllByUserId(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllByUserId", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.BookLoanService.ResponseOfDataTable> GetAllByUserIdAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LibrarySystem.App.BookLoanService.ResponseOfBoolean Delete(int borrowId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<LibrarySystem.App.BookLoanService.ResponseOfBoolean> DeleteAsync(int borrowId);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BorrowCreateDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int uIDField;
        
        private string iSBNField;
        
        private System.DateTime returnDateField;
        
        private System.DateTime borrowDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int UID {
            get {
                return this.uIDField;
            }
            set {
                this.uIDField = value;
                this.RaisePropertyChanged("UID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ISBN {
            get {
                return this.iSBNField;
            }
            set {
                this.iSBNField = value;
                this.RaisePropertyChanged("ISBN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ReturnDate {
            get {
                return this.returnDateField;
            }
            set {
                this.returnDateField = value;
                this.RaisePropertyChanged("ReturnDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime BorrowDate {
            get {
                return this.borrowDateField;
            }
            set {
                this.borrowDateField = value;
                this.RaisePropertyChanged("BorrowDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResponseOfBoolean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string messageField;
        
        private bool dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResponseOfDataTable : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string messageField;
        
        private System.Data.DataTable dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Data.DataTable Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BorrowReturnDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int bIDField;
        
        private System.DateTime actualReturnDateField;
        
        private decimal lateFeeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int BID {
            get {
                return this.bIDField;
            }
            set {
                this.bIDField = value;
                this.RaisePropertyChanged("BID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime ActualReturnDate {
            get {
                return this.actualReturnDateField;
            }
            set {
                this.actualReturnDateField = value;
                this.RaisePropertyChanged("ActualReturnDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal LateFee {
            get {
                return this.lateFeeField;
            }
            set {
                this.lateFeeField = value;
                this.RaisePropertyChanged("LateFee");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BorrowViewDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int bIDField;
        
        private string iSBNField;
        
        private System.DateTime returnDateField;
        
        private System.DateTime actualReturnDateField;
        
        private decimal lateFeeField;
        
        private System.DateTime borrowDateField;
        
        private string bookNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int BID {
            get {
                return this.bIDField;
            }
            set {
                this.bIDField = value;
                this.RaisePropertyChanged("BID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ISBN {
            get {
                return this.iSBNField;
            }
            set {
                this.iSBNField = value;
                this.RaisePropertyChanged("ISBN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ReturnDate {
            get {
                return this.returnDateField;
            }
            set {
                this.returnDateField = value;
                this.RaisePropertyChanged("ReturnDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime ActualReturnDate {
            get {
                return this.actualReturnDateField;
            }
            set {
                this.actualReturnDateField = value;
                this.RaisePropertyChanged("ActualReturnDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal LateFee {
            get {
                return this.lateFeeField;
            }
            set {
                this.lateFeeField = value;
                this.RaisePropertyChanged("LateFee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime BorrowDate {
            get {
                return this.borrowDateField;
            }
            set {
                this.borrowDateField = value;
                this.RaisePropertyChanged("BorrowDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string BookName {
            get {
                return this.bookNameField;
            }
            set {
                this.bookNameField = value;
                this.RaisePropertyChanged("BookName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResponseOfBorrowViewDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string messageField;
        
        private BorrowViewDto dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public BorrowViewDto Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BookLoanSoapServiceSoapChannel : LibrarySystem.App.BookLoanService.BookLoanSoapServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookLoanSoapServiceSoapClient : System.ServiceModel.ClientBase<LibrarySystem.App.BookLoanService.BookLoanSoapServiceSoap>, LibrarySystem.App.BookLoanService.BookLoanSoapServiceSoap {
        
        public BookLoanSoapServiceSoapClient() {
        }
        
        public BookLoanSoapServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookLoanSoapServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookLoanSoapServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookLoanSoapServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LibrarySystem.App.BookLoanService.ResponseOfBorrowViewDto Borrow(LibrarySystem.App.BookLoanService.BorrowCreateDto dto) {
            return base.Channel.Borrow(dto);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.BookLoanService.ResponseOfBorrowViewDto> BorrowAsync(LibrarySystem.App.BookLoanService.BorrowCreateDto dto) {
            return base.Channel.BorrowAsync(dto);
        }
        
        public LibrarySystem.App.BookLoanService.ResponseOfBorrowViewDto Return(LibrarySystem.App.BookLoanService.BorrowReturnDto dto) {
            return base.Channel.Return(dto);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.BookLoanService.ResponseOfBorrowViewDto> ReturnAsync(LibrarySystem.App.BookLoanService.BorrowReturnDto dto) {
            return base.Channel.ReturnAsync(dto);
        }
        
        public LibrarySystem.App.BookLoanService.ResponseOfBorrowViewDto GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.BookLoanService.ResponseOfBorrowViewDto> GetByIdAsync(int id) {
            return base.Channel.GetByIdAsync(id);
        }
        
        public LibrarySystem.App.BookLoanService.ResponseOfDataTable GetUnreturnedLoansByUserId(int userId) {
            return base.Channel.GetUnreturnedLoansByUserId(userId);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.BookLoanService.ResponseOfDataTable> GetUnreturnedLoansByUserIdAsync(int userId) {
            return base.Channel.GetUnreturnedLoansByUserIdAsync(userId);
        }
        
        public LibrarySystem.App.BookLoanService.ResponseOfDataTable GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.BookLoanService.ResponseOfDataTable> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public LibrarySystem.App.BookLoanService.ResponseOfDataTable GetAllByUserId(int userId) {
            return base.Channel.GetAllByUserId(userId);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.BookLoanService.ResponseOfDataTable> GetAllByUserIdAsync(int userId) {
            return base.Channel.GetAllByUserIdAsync(userId);
        }
        
        public LibrarySystem.App.BookLoanService.ResponseOfBoolean Delete(int borrowId) {
            return base.Channel.Delete(borrowId);
        }
        
        public System.Threading.Tasks.Task<LibrarySystem.App.BookLoanService.ResponseOfBoolean> DeleteAsync(int borrowId) {
            return base.Channel.DeleteAsync(borrowId);
        }
    }
}
